# Generated by Django 4.0.1 on 2022-02-05 16:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base_page_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='employee',
            field=models.ManyToManyField(null=True, related_name='employee', to=settings.AUTH_USER_MODEL),
        ),
    ]
