# Generated by Django 4.0.1 on 2022-02-12 08:49

import datetime
from django.conf import settings
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base_page_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='employee',
            field=models.ManyToManyField(blank=True, related_name='employee', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='todo',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 2, 12, 8, 49, 31, 760220, tzinfo=utc)),
        ),
    ]
