# Generated by Django 4.0.1 on 2022-02-12 12:24

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('base_page_app', '0002_alter_company_employee_alter_todo_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 2, 12, 12, 24, 3, 266154, tzinfo=utc)),
        ),
    ]
