# Generated by Django 4.0.1 on 2022-02-06 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_page_app', '0004_alter_company_creator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='in_progress',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='todo',
            name='is_done',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
