# Generated by Django 4.0.1 on 2022-02-06 12:22

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('base_page_app', '0007_alter_todo_description_alter_todo_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 2, 6, 12, 22, 51, 381845, tzinfo=utc)),
        ),
    ]
